### ISSUE TITLE
"This page will be reachable"-url is not correctly build with sluggi

### ISSUE THREAD

**Issue by datango** [wazum/sluggi#29] opened 2020-05-14 07:32 UTC
Without sluggi
This page will be reachable via https://server.de/demo/area/test/example

With sluggi - last_segment_only off
This page will be reachable via https://server.de/area/test/example
Slug: [https://server.de/demo]/area/test/example
[] not accessible

With sluggi - last_segment_only on
This page will be reachable via https://server.de/example
Slug: [https://server.de/demo/area/test]/example
[] not accessible

**Comment by datango** [comment] 2020-05-14 07:33
@wazum : Now i'm using TYPO3 9.5.17

**Comment by wazum** [comment] 2020-06-02 16:03
@datango  which extension version? Can't reproduce this.

**Comment by wazum** [comment] 2020-06-15 14:23
Is fixed in the latest versions

**Closed by wazum** 2020-06-15 14:23 UTC
Labels: feedback needed
