### ISSUE TITLE
InvalidArgumentException in redirects after rename a slug of a page twice 

### ISSUE THREAD

**Issue by kanow** [wazum/sluggi#6] opened 2019-09-03 15:07 UTC
Hi,
I checked out the version 1.2.1 of sluggi but I have following problems:
 I renamed a page to a new slug, and renamed it back to the slug before.
After this I tried to open the redirect module. 

```
(1/1) #1526127158 InvalidArgumentException
Uid must be a positive integer, given.

in /app/web/typo3/sysext/backend/Classes/ViewHelpers/Link/EditRecordViewHelper.php line 69
```
The slug fields on child pages are not changed too. I thought, they will be changed recursively if I change the slug on parent page. There is those setting (Rename slug segments recursively) in extension configuration. It doesn't work for the moment?

**Comment by wazum** [comment] 2019-09-26 04:49
Hi, thanks for the report, unfortunately I can't reproduce this. Try the most recent version (dev-master) and see if that helps.

Please take a look at the sys_redirect table and check the incorrect record, what values are set there?

Recursively: yes, works for me (and others).

Did you do all these actions as an Administrator or regular editor (with certain permissions)?

**Comment by wazum** [comment] 2019-10-01 12:01
I'm closing this as there's no feedback.

**Closed by wazum** 2019-10-01 12:01 UTC
Labels: question
